spring:
  application:
    name: fraud-detection-management-api
  datasource:
    driver-class-name: org.postgresql.Driver

camel:
  rest:
    component: jetty
    port: 8080
    binding-mode: json
  component:
    kafka:
      group-id: fraud-detection-management-api