spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update

camel:
  component:
    kafka:
      brokers: localhost:29092